[project]
name = "road-network-prolog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    # "geoalchemy2>=0.18.0",
    # "networkx>=3.5",
    # "osmium>=4.2.0",
    # "psycopg2>=2.9.11",
    "pydantic>=2.12.3",
    # "python-dotenv>=1.1.1",
    "pyswip>=0.3.3",
    "rich>=14.2.0",
    # "shapely>=2.1.2",
    # "sqlmodel>=0.0.27",
    "ttkbootstrap>=1.16.0",
]
